"""
EnumTools
"""
from enum import Enum
from typing import Any, Iterable, TypeVar, Union, Callable

_CT = TypeVar('_CT', covariant=True)
_CRT = TypeVar('_CRT', covariant=True)
_CF = Union[Callable[..., _CRT], _CRT]

def is_enum(obj: Any) -> bool: ...
def members(e: Enum) -> Iterable: ...

def valueof(v: Any, e: Enum = ...) -> _CF: ...
def nameof(name: str, e: Enum = ...) -> _CF: ...

def e_index_of(m: Any, e: Enum = ...) -> _CF: ...
def e_index_by(i: int, e: Enum = ...) -> _CF: ...

def enum_name(e: Enum) -> str: ...
def enum_value(e: Enum) -> Any: ...
